# Generated by Django 2.1.7 on 2019-05-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon',
            new_name='Discount',
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'ფასდაკლება'},
        ),
    ]
