# Generated by Django 2.1.7 on 2019-05-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20190527_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': ' ფასდაკლება'},
        ),
    ]
