# Generated by Django 2.1.7 on 2019-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_programers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programers',
            new_name='Programmers',
        ),
    ]
