# Generated by Django 2.1.7 on 2019-05-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190523_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmers',
            options={'verbose_name_plural': 'Programers'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': "todo's"},
        ),
        migrations.AddField(
            model_name='programmers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
