# Generated by Django 2.1.7 on 2019-05-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='დასახელება')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y%m%d', verbose_name='პროდუქტის გამოსახულება')),
                ('description', models.CharField(max_length=200, verbose_name='პროდუქტის აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('stock', models.PositiveIntegerField(verbose_name='საწყობშია')),
                ('available', models.BooleanField(default=True, verbose_name='ხელმისაწვდომია')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='კატეგორია')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
